version: "3"

networks:
  compose-network:
    driver: bridge

volumes:
  postgres:
  pgadmin:

services:
  web:
    image: sicemal/kube-news:v1
    restart: always
    build:
      dockerfile: ./Dockerfile
      context: ./
    ports:
      - 8080:8080
    networks:
      - compose-network
    depends_on:
      - postgres
    environment:
      DB_NAME: "kubedevnews"
      DB_USERNAME: ${POSTGRES_USER:-postgres}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      DB_HOST: postgres_container

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - compose-network
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      #PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      #PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      #PGADMIN_DEFAULT_EMAIL: "silvio@gmail.com"
      #PGADMIN_DEFAULT_PASSWORD: "123456"
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-silvio@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-123456}
      PGADMIN_CONFIG_SERVER_MODE: "True"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - compose-network
    restart: unless-stopped
